### ISSUE TITLE
Frequent Keepalive Timeouts

### ISSUE THREAD

**Issue by uHACsTx** [nicocha30/ligolo-ng#101]
**Description**
When establishing a double pivot, I frequently receive a yamux EOF error, which manifests in a timeout and a dead or stopped connection. Sometimes the agent just closes, but sometimes ligolo has to be restarted, including the proxy, to make it work again.

**Reproducing the Error**
- Start the proxy with ./proxy -selfcert
- Create the ligolo interface, set it up and create a route to the target network
- Connect an agent from a remote machine
- Create a listener in this session
- Create a second interface, set it up and add a route to the second internal target network
- Connect an agent from an internal host
- Wait or produce traffic

**Expected behavior**
The connection should not stop.

**Screenshots**
![image](https://github.com/user-attachments/assets/423ba724-a87d-4929-887b-ee7338c5f281)

**Proxy information:**
 - OS: [Recent Arch Linux]
 - Architecture [amd64]
 - Version [ligolo-0.5.2] (A connection was not even possible with newer agents due to this error)

**Agent information:**
 - OS: [Ubuntu Linux, Windows Server 2019]
 - Architecture [amd64]
 - Version [ligolo-0.5.2] (A connection was not even possible with newer agents due to this error)

**Additional context**
I was using the agent in the CPTS exam. The network connection might have been slow.

**Comment by nicocha30** [comment]
"Keep Alive Timeout" errors are mainly caused by an unstable network or a loss of TCP connection.
The latest version of Ligolo-ng (v0.7), still in alpha, supports automatic recovery of tunnels and listeners.
You can run the agent with the -retry option to automatically retry the connection.
