### ISSUE TITLE
Set the alpha version as pre-release

### ISSUE THREAD

**Issue by vincentbenzo** [nicocha30/ligolo-ng#107]
Expected behavior:
Having the latest production ready set as latest release.
Having release-candidate set as pre-release.

Observed behavior:
The latest release is not production ready :
https://github.com/nicocha30/ligolo-ng/releases/tag/v0.7.2-alpha

The use case for this request is to give the possibility to automate the installation of the latest production ready using ansible.

Thank you for this amazing tool !

![prerelease](https://github.com/user-attachments/assets/456b3db4-075f-41a6-b46b-268178231c8a)

**Comment by goproslowyo** [comment]
Yea an alpha shouldn't be marked as "latest". I just ran into this too. Unless you're ready to cut a release mark it as pre-release please.

**Comment by goproslowyo** [comment]
Interesting @nicocha30.
>  "nicocha30 (Nicolas Chatelain) closed this as not planned yesterday" 

Meaning you don't plan to follow a reasonable release process? This makes packaging your application by upstream distros hard (or even not possible). e.g. this will likely never get packaged by Debian/Ubuntu without it.

```
$ sudo apt search ligolo
Sorting... Done
Full Text Search... Done

$ sudo apt search ligolo-ng
Sorting... Done
Full Text Search... Done
```

**Comment by nicocha30** [comment]
@goproslowyo, I've closed this issue because there is no longer an alpha version. The latest version of Ligolo-ng is normally stable.
Furthermore, I'm not looking to integrate Ligolo-ng on Debian/Ubuntu repositories. However, this shouldn't be a problem, as Kali integrates Ligolo-ng.
In future, I'll mark test versions as pre-release.

**Comment by goproslowyo** [comment]
Thank you much, happy new year!
