### ISSUE TITLE
[BUG] ERRO[3087] could not register agent, error: session shutdown

### ISSUE THREAD

**Issue by Bruno-Macedo** [nicocha30/ligolo-ng#110]
**Describe the bug**
I've been experienced this issue for a couple of times when I use ligolo:
1. First tunneling: works perfect (Linux <=> Linux:Zone 1)
2. Double tunneling: Agent could not register (Linux <=> Linux:Zone 1 <==> Windows: Zone 2

For the first tunnel, I upload the agent to the Linux Pivot machine. In the Attacker machine I start the proxy:
```
./proxy -selfcert
session 1
start
```

On the Attacker I create an interface;
```
sudo ip tuntap add user USERNAME mode tun ligolo
sudo ip link set ligolo up
```

After that I can connect to all hosts on Zone 1.

For the double pivot I do the following:
```
# Attacker
sudo ip tuntap add user kaliwork mode tun ligolo-double
sudo ip link set ligolo-double up

# Attacker in Ligolo
listener_add --addr 0.0.0.0:11601 --to 127.0.0.1:11601 --tcp
```

I upload the agent to the Host that connects to Zone 2 and issue the next command on this host:
```
.\agent.exe -connect IP_OF_FIRST_PIVOT:11601 -ignore-cert
I use the internal IP of the pivot 1
Attacker <========>public_ip | PIVOT 1| internal_ip <=============> Pivot 2
```

I see that the tool is executed, but in proxy i receive the following error message:
```
ERRO[3087] could not register agent, error: session shutdown
2024/10/14 22:34:28 [ERR] yamux: Failed to write header: EOF
```

On the agent, where the pivot 2 should work, I get the following message:
```
 .\agent.exe -connect 172.16.1.100:11601 -ignore-cert
agent.exe : time="2024-10-14T20:50:34+01:00" level=warning msg="warning, certificate validation disabled"
    + CategoryInfo          : NotSpecified: (time="2024-10-1...ation disabled":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
time="2024-10-14T20:50:34+01:00" level=info msg="Connection established" addr="172.16.1.100:11601"
time="2024-10-14T20:50:34+01:00" level=error msg="msgpack: unexpected code=21 decoding map length"
^C
```

Am I doing anything wrong? I have followed the tutorials below:
- [Very good tutorial](https://www.hackingarticles.in/a-detailed-guide-on-ligolo-ng/)
- [Official Ligolo-ng](https://github.com/nicocha30/ligolo-ng)
- [Another tutorial](https://arth0s.medium.com/ligolo-ng-pivoting-reverse-shells-and-file-transfers-6bfb54593fa5)
- [Also very good](https://www.stationx.net/how-to-use-ligolo-ng/)
- [Tunneling like a VPN](https://4pfsec.com/ligolo)

Kind Regards,
Bruno

**Comment by nicocha30** [comment]
This bug is most likely due to protocol incompatiblity between the agent and the proxy. Make sure you use the same agent and proxy version.
