### ISSUE TITLE
ligolo-ng proxy for pfsense

### ISSUE THREAD

**Issue by dr4mohamed** [nicocha30/ligolo-ng#119]
ligolo-ng proxy for pfsense
 i can't compile for pfsense i get errors
 can you provide package for pfsense easy to install

#  go build -o proxy cmd/proxy/main.go
# github.com/nicocha30/ligolo-ng/pkg/proxy/netstack/tun
pkg/proxy/netstack/tun/wireguard_ep.go:57:34: undefined: offset
pkg/proxy/netstack/tun/wireguard_ep.go:70:40: undefined: offset
pkg/proxy/netstack/tun/wireguard_ep.go:73:34: undefined: offset
pkg/proxy/netstack/tun/wireguard_ep.go:106:28: undefined: offset
pkg/proxy/netstack/tun/wireguard_ep.go:108:66: undefined: offset

**Comment by nicocha30** [comment]
Release 0.7.3 now supports BSD.
Tested today on pfsense, it works!

Once Ligolo-ng is started and the `start` command is executed, a new "Ligolo" interface will appear. You need to register this interface in "Interfaces / Interface Assignments" (dont' setup any IP).

![Capture d’écran du 2024-12-10 10-37-48](https://github.com/user-attachments/assets/eec53330-0e53-4097-8cb8-228b8acf1f96)

Then, create a Ligolo-ng gateway in "System / Routing / Gateways"

![Capture d’écran du 2024-12-10 10-35-04](https://github.com/user-attachments/assets/b040f8ae-ff66-4cf4-9724-56f25fee4e60)

After that, you can create new routes and tunnel connections to Ligolo-ng :smiley: 

![Capture d’écran du 2024-12-10 10-35-14](https://github.com/user-attachments/assets/d0de007b-a946-4eb4-89a6-878f6cce39a5)

**Comment by dr4mohamed** [comment]
thanks,

i can't add new route for every session 

`[2.7.2-RELEASE][root@pfSense]/var: ./proxy -selfcert
WARN[0000] Using default selfcert domain 'ligolo', beware of CTI, SOC and IoC! 
WARN[0000] Using self-signed certificates               
WARN[0000] TLS Certificate fingerprint for ligolo is: 51BEB01D91447263BF1D03E25F14EAFE3D073245DE5F449C22A4A32EE2DC33AE 
INFO[0000] Listening on 0.0.0.0:11601                   
    __    _             __                       
   / /   (_)___ _____  / /___        ____  ____ _
  / /   / / __ `/ __ \/ / __ \______/ __ \/ __ `/
 / /___/ / /_/ / /_/ / / /_/ /_____/ / / / /_/ / 
/_____/_/\__, /\____/_/\____/     /_/ /_/\__, /  
        /____/                          /____/   

  Made in France ♥            by @Nicocha30!
  Version: 0.7.3

ligolo-ng » INFO[0009] Agent joined.                                 id=00222a4c-2526-49af-9625-7de783f9df91 name="WIN-57OTHVTJ5PB\\Administrator@WIN-57OTHVTJ5PB" remote="192.168.1.179:49835"
ligolo-ng » 
ligolo-ng » session 
? Specify a session : 1 - WIN-57OTHVTJ5PB\Administrator@WIN-57OTHVTJ5PB - 192.168.1.179:49835 - 00222a4c-2526-49af-9625-7de783f9df91
[Agent : WIN-57OTHVTJ5PB\Administrator@WIN-57OTHVTJ5PB] » 
[Agent : WIN-57OTHVTJ5PB\Administrator@WIN-57OTHVTJ5PB] » 
[Agent : WIN-57OTHVTJ5PB\Administrator@WIN-57OTHVTJ5PB] » 
[Agent : WIN-57OTHVTJ5PB\Administrator@WIN-57OTHVTJ5PB] »  
certificate_fingerprint    clear                      connect_agent              exit                       help                       ifconfig                   
listener_add               listener_list              listener_stop              session                    tunnel_list                tunnel_start               
tunnel_stop                
`

**Comment by nicocha30** [comment]
interface_* commands are only available on Linux.
You should follow the steps mentioned on my previous reply to add routes.

**Comment by nicocha30** [comment]
@blkthunda which release did you used?

**Comment by blkthunda** [comment]
I used FreeBSD agent 7.5 and 7.3

**Comment by blkthunda** [comment]
@nicocha30 Did I use the right releases? Please let me what I should do for this to work with FreeBSD. Thank you!
