### ISSUE TITLE
client-retries register as new sessions on proxy

### ISSUE THREAD

**Issue by audibleblink** [nicocha30/ligolo-ng#12]
is there currently any notion of session data exchanged between client and proxy?
during network hiccups, it's great to get a connection back, but it creates a new session on the proxy that forces a user to tab  back over and re-select and start the session.

if a user is on another windows/workspace/terminal, they might not be aware the connection has restarted and they're left wondering why tool $x isn't working anymore

**Comment by nicocha30** [comment]
It took a while, but Ligolo-ng v0.7.0-alpha now implements session management, and is capable of automatically restarting tunnels and listeners.
