### ISSUE TITLE
[BUG] Listener not working for file transfers in version 0.7.3

### ISSUE THREAD

**Issue by royaliceblue** [nicocha30/ligolo-ng#126]
**Describe the bug**
In a scenario where a file transfer is required, a listener will be set up. However, in 0.7.3 the transfer does not work almost everytime. 

**However, when tested in version 0.4.3, it works smoothly.**

**To Reproduce**
1. sudo ./proxy -selfcert -laddr 0.0.0.0:443
2. ligolo-agent.exe -connect 192.168.85.128:443 -ignore-cert
3. listener_add --addr 0.0.0.0:1235 --to 127.0.0.1:80
4. certutil -urlcache -f is used to initiate the file transfer. However, no file transfer takes place with the error message shown in screenshot below.

**Expected behavior**
The file transfer should be successful.

**Screenshots**
<img width="500" alt="image" src="https://github.com/user-attachments/assets/31acae74-4601-4083-be34-87995b26e79b" />

**Proxy information:**
[ligolo-ng_proxy_0.7.3_linux_amd64.tar.gz](https://github.com/nicocha30/ligolo-ng/releases/download/v0.7.3/ligolo-ng_proxy_0.7.3_linux_amd64.tar.gz)

**Agent information:**
[ligolo-ng_agent_0.7.3_windows_amd64.zip](https://github.com/nicocha30/ligolo-ng/releases/download/v0.7.3/ligolo-ng_agent_0.7.3_windows_amd64.zip)

**Additional context**
As mentioned, when tested in version 0.4.3, it works smoothly.

**Comment by nicocha30** [comment]
Can you try with the latest version (0.7.4)?

**Comment by havoc3-3** [comment]
Same issue with 0.7.4, same binaries listed above.
