### ISSUE TITLE
unexistend ip reply to ping, why?

### ISSUE THREAD

**Issue by ghost** [nicocha30/ligolo-ng#13]
hi, i tried use your tool, but i have problem, i receive ping from all 255 ips from my network.  
I can ping any unexistend ip from my network. why?

only these ip are live in network:

```
Discovered open port 3389/tcp on 192.168.0.1
Discovered open port 3389/tcp on 192.168.0.146
Discovered open port 3389/tcp on 192.168.0.147
```

```
map 192.168.0.0/24 -p 3389 -v -n
```

**Comment by connected201** [comment]
```
Starting Nmap 7.92 ( https://nmap.org ) at 2022-03-21 11:15 EDT
Initiating Ping Scan at 11:15
Scanning 256 hosts [4 ports/host]
Completed Ping Scan at 11:15, 0.04s elapsed (256 total hosts)
Initiating SYN Stealth Scan at 11:15
Scanning 256 hosts [1 port/host]
Discovered open port 3389/tcp on 192.168.0.1
Discovered open port 3389/tcp on 192.168.0.146
Discovered open port 3389/tcp on 192.168.0.147
Completed SYN Stealth Scan at 11:15, 1.35s elapsed (256 total ports)
Nmap scan report for 192.168.0.0
Host is up (0.00016s latency).
PORT     STATE    SERVICE
3389/tcp filtered ms-wbt-server
Nmap scan report for 192.168.0.1
Host is up (0.039s latency).
PORT     STATE SERVICE
3389/tcp open  ms-wbt-server
Nmap scan report for 192.168.0.2
Host is up (0.000093s latency).
PORT     STATE    SERVICE
3389/tcp filtered ms-wbt-server
Nmap scan report for 192.168.0.3
Host is up (0.000094s latency).
PORT     STATE    SERVICE
3389/tcp filtered ms-wbt-server
Nmap scan report for 192.168.0.4
Host is up (0.00011s latency).
PORT     STATE    SERVICE
3389/tcp filtered ms-wbt-server
Nmap scan report for 192.168.0.5
Host is up (0.00012s latency).
```

**Comment by connected201** [comment]
also if i run scan `nmap 192.168.0.0/24 -p 3389 -v -sV -n`  
in server console i receive:

![](https://user-images.githubusercontent.com/20506433/159295668-df2a33d6-6e22-49bc-9327-e24cc643f80d.png)

**Comment by d4vid1710** [comment]
Hello,

I have the same problem.

When pinging an IP that does not exist/reply, there is fake reply immediately.
Example (10.100.100.5 does not exist):
![ping1](https://user-images.githubusercontent.com/102759464/161123987-8e22fb68-e843-4755-adaf-b38245362420.jpg)

But when pinging an IP address that exists/replies, there are 2 replies (the first one, fake, and then the "real one"):
Example (10.100.100.1 exists):
![ping2](https://user-images.githubusercontent.com/102759464/161124030-fff29135-4fa0-4433-a0a6-6d6be80bb032.jpg)

Would it be possible to suppress the first "systematic" reply and keep only the second one (when host is up)?

Thank you.

**Comment by Nicocha30** [comment]
Hello,

Thanks for reporting. This issue is caused by a Gvisor update. I will investigate and keep you updated.

**Comment by Nicocha30** [comment]
Should be fixed! I downgraded gvisor.
