### ISSUE TITLE
Ligolo blocks after TCP scanning

### ISSUE THREAD

**Issue by d4vid1710** [nicocha30/ligolo-ng#14]
Hello,

When launching a network scanning (TCP connect scan) through Ligolo, I realized that the TCP outbound connections were blocked after a few minutes.

Example of scan with nmap:
`nmap 10.100.100.0/16 -p- -sT -Pn -T5`

At the beginning of the scan, I'm able to connect every TCP port through the ligolo interface.
After a few minutes (~10 mins), all the TCP connection attemps fail.

When relaunching the server (proxy) with the agent set to "auto retry", it works again.

Is there a limit on the number of connections that Ligolo server can accept?

Thank you.

**Comment by nicocha30** [comment]
Hello,

Release v0.4 fixed this issue. Max TCP inflight connections are now configurable.
