### ISSUE TITLE
ligolo-ng proxy error handling for missing tun interface

### ISSUE THREAD

**Issue by noraj** [nicocha30/ligolo-ng#16]
I'm using [ligolo-ng_proxy_0.3.3_Linux_64bit.tar.gz](https://github.com/nicocha30/ligolo-ng/releases/download/v0.3.3/ligolo-ng_proxy_0.3.3_Linux_64bit.tar.gz).

But when launching the proxy it seems to have an error with the tun interface.

```
./proxy -laddr 192.168.1.26:11601 -selfcert 
panic: tun.Open: no such device

goroutine 1 [running]:
ligolo-ng/pkg/proxy/netstack.(*NetStack).new(0xc00000d350, {0x9dce33, 0x6})
        /home/runner/work/ligolo-ng/ligolo-ng/pkg/proxy/netstack/stack.go:176 +0x688
ligolo-ng/pkg/proxy/netstack.NewStack(...)
        /home/runner/work/ligolo-ng/ligolo-ng/pkg/proxy/netstack/stack.go:87
ligolo-ng/cmd/proxy/app.Run({0x9dce33, 0x6})
        /home/runner/work/ligolo-ng/ligolo-ng/cmd/proxy/app/app.go:55 +0xd2
main.main()
        /home/runner/work/ligolo-ng/ligolo-ng/cmd/proxy/main.go:38 +0x2a6
```

It is because I forget to create a tun interface before.

```
$ sudo ip tuntap add user [your_username] mode tun ligolo
$ sudo ip link set ligolo up
```

So instead of unhandled error could ligolo handle the error and send an error message like `no ligolo tun interface detected, verify that you created and started the tun interface`? `tun.Open: no such device` is already a bit but it could be more explicit.
This is especially common to forgot recreating the tun interface after a reboot.

**Comment by nicocha30** [comment]
Release v0.4 fixed this issue: error messages are a bit more explicit now
