### ISSUE TITLE
Proxy agent starter

### ISSUE THREAD

**Issue by dewest91** [nicocha30/ligolo-ng#24]
This is probably a user issue, but I'm unable to start the proxy on the server side.  Could you provide syntax for how to start the proxy listener?
![image](https://user-images.githubusercontent.com/26369082/190212760-48c6049f-a206-4752-9d00-439aa49fac49.png)

**Comment by 0xswitch** [comment]
I think that agent and proxy have been switched at compile time. Try ./agent instead.
