### ISSUE TITLE
[Request] Ligolo-NG over UDP

### ISSUE THREAD

**Issue by cmprmsd** [nicocha30/ligolo-ng#25]
Hey there!

Would it be possible to encapsulate the traffic within UDP in order to bypass firewalls?
I assume many companies block outgoing TCP but allow e.g. 53, 123, 161 or 500 over UDP.

From the code it looks like the TLS implementation does need TCP.

**Comment by nicocha30** [comment]
Hey! Yes, it should be possible. However, Yamux requires a reliable and ordered underlying connection (which is not the case with UDP). You should take a look at [kcp-go](https://github.com/xtaci/kcp-go).
