### ISSUE TITLE
Multiple routes to agent's network

### ISSUE THREAD

**Issue by virusvfv** [nicocha30/ligolo-ng#31]
What if we have multiple agents from different client networks. (Ex: agentA from 192.168.5.0/24 and agentB  from 172.16.88.0/24) and want to work with this nets...?
Now we must choose in what session start tunnel. Other  session will be usefulness.
Lets make agents and its routes work simultaneously !

I think that easy way to do this - creating separate tap interface for separate agent when U type start in agent session. So on proxy there will be many ligolo interfaces, each for specific agent. When agent falls interface is deleted by proxy.

**Comment by nicocha30** [comment]
Implemented in Ligolo-ng v0.5 :wink:

**Comment by KNulL0** [comment]
I have the same question. May I ask how should I proceed?

**Comment by nicocha30** [comment]
> I have the same question. May I ask how should I proceed?

@KNulL0 

Create another *tuntap* interface, and specify the new interface by using the `--tun ligolo2` parameter of the `start` command.

**Comment by KNulL0** [comment]
> > 我也有同样的问题。请问我应该如何进行？
> 
> @KNulL0
> 
> 创建另一个_tuntap_接口，并通过命令`--tun ligolo2`的参数指定新接口`start`。

Thanks
