### ISSUE TITLE
Ligolo doesn't work with golang version 20

### ISSUE THREAD

**Issue by QU35T-code** [nicocha30/ligolo-ng#32]
Hello,

There is a problem with the proxy build (agent is ok) with `golang version 20`. The build with `version 19` is functional but an error occurs with version 20.

```bash
root@f33e8b06d6cc:/opt/tools/ligolo-ng# wget -O /tmp/go.tar.gz https://go.dev/dl/go1.19.linux-arm64.tar.gz

Saving to: '/tmp/go.tar.gz'

root@f33e8b06d6cc:/opt/tools/ligolo-ng# tar -C /usr/local -xzf /tmp/go.tar.gz
root@f33e8b06d6cc:/opt/tools/ligolo-ng# /usr/local/go/bin/go build -o proxy cmd/proxy/main.go

[...BUILD OK...]
```

```bash
root@f33e8b06d6cc:/opt/tools/ligolo-ng# wget -O /tmp/go.tar.gz https://go.dev/dl/go1.20.linux-arm64.tar.gz

Saving to: '/tmp/go.tar.gz'

root@f33e8b06d6cc:/opt/tools/ligolo-ng# tar -C /usr/local -xzf /tmp/go.tar.gz
root@f33e8b06d6cc:/opt/tools/ligolo-ng# /usr/local/go/bin/go build -o proxy cmd/proxy/main.go

# github.com/nicocha30/gvisor-ligolo/pkg/gohacks
/root/go/pkg/mod/github.com/nicocha30/gvisor-ligolo@v0.0.0-20230201100237-f26fe0a6c03c/pkg/gohacks/string_go120_unsafe.go:27:7: unsafe.StringData requires go1.20 or later (-lang was set to go1.18; check go.mod)
/root/go/pkg/mod/github.com/nicocha30/gvisor-ligolo@v0.0.0-20230201100237-f26fe0a6c03c/pkg/gohacks/string_go120_unsafe.go:38:9: unsafe.String requires go1.20 or later (-lang was set to go1.18; check go.mod)
```

**Comment by dismantl** [comment]
Possibly related to this issue: https://github.com/golang/go/issues/58554

I haven't tried this yet but I expect upgrading gvisor-ligolo to the latest upstream gvisor may solve this problem, as [upstream now sets go1.20 as the minimum version](https://github.com/google/gvisor/blob/16f76ac49329d435983c4e3ec71db17d88eabecd/go.mod#L3).

I'd be happy to submit a PR but am unsure exactly what changes the fork has. I see that [ICMP handling was removed](https://github.com/nicocha30/gvisor-ligolo/commit/fbb9ed56c019a9fe028edb8f8391aed00007b6d9), but are there other changes too?

**Comment by dismantl** [comment]
I was able to get ligolo-ng to build successfully with go 1.20 by using an [updated gvisor fork](https://github.com/dismantl/gvisor). Here's the [branch I used](https://github.com/dismantl/ligolo-ng/tree/go1.20), and you can see that there are a [few minor changes needed](https://github.com/dismantl/ligolo-ng/commit/3b02928cfc0fa4aa99cc6255b088794b8a2fff78) relating to updated type definitions in the latest gvisor.

**Comment by ikstream** [comment]
Hi, are there any updates on this @nicocha30?

**Comment by nicocha30** [comment]
Hey,

I'm working on it today. Will keep you updated.

Nicolas

**Comment by ikstream** [comment]
Thank you very much

**Comment by ikstream** [comment]
Thank you, works like a charm, as far as I can tell.
