### ISSUE TITLE
got erros if try to scan ip

### ISSUE THREAD

**Issue by useragent23253** [nicocha30/ligolo-ng#33]
Hello, I've got these erorrs if try to scan 
ERRO[11480] connection was refused                       
ERRO[11480] connection was refused                       
ERRO[11480] connection was refused                       
ERRO[11480] connection was refused                       
ERRO[11480] connection was refused                       
ERRO[11480] connection was refused                       
ERRO[11480] connection was refused
I was using the latest release. How to solve it? Thanks in advanced

**Comment by 1oftheguthakrs** [comment]
I have the same error message.
I am using Kali Linux
`` ./proxy -selfcert`` 
On Microsoft Windows [Version 10.0.19044.2251], I run
`` .\agent.exe -connect IP:11601 -ignore-cert`` 

This error shows up when I do nmap -Pn -p- single_ip
