### ISSUE TITLE
Networking Speed Degraded

### ISSUE THREAD

**Issue by cmprmsd** [nicocha30/ligolo-ng#34]
It seems some updates degraded the networking speed a lot. 
I tested this locally within my LAN. Don't get confused by the interface type. The connection is from VM to host and not affected by Wifi speed.

Routed via ligolo-ng:
![image](https://user-images.githubusercontent.com/73472903/221229485-5f13008a-d7b8-44b2-a5bc-88394927db36.png)

Direct connection:
![image](https://user-images.githubusercontent.com/73472903/221229666-35fe99ed-4861-4b07-a53d-b0c15e0a1a83.png)

This differs quite heavily from your benchmarks and I wonder why and what could be optimized. :blush:

**Comment by nicocha30** [comment]
Hey @cmprmsd, I have done some tests locally.

Without ligolo-ng:

```
[SUM]   0.00-10.00  sec   439 MBytes   368 Mbits/sec  159             sender
[SUM]   0.00-10.02  sec   414 MBytes   347 Mbits/sec                  receiver
```

With ligolo-ng:

```
[SUM]   0.00-10.00  sec   336 MBytes   282 Mbits/sec  3312             sender
[SUM]   0.00-10.05  sec   320 MBytes   267 Mbits/sec                  receiver
```

So your results are a bit strange. Can you tell me more about your setup?

**Comment by cmprmsd** [comment]
Thanks for your quick response @nicocha30. 
I retested with different hosts and the problem is not that visible there.

without ligolo-ng:
```
[  5]   0.00-10.00  sec   696 MBytes   584 Mbits/sec   55             sender
[  5]   0.00-10.00  sec   693 MBytes   581 Mbits/sec                  receiver
```

with ligolo-ng:
```
[  5]   0.00-10.00  sec   328 MBytes   275 Mbits/sec    4             sender
[  5]   0.00-10.01  sec   326 MBytes   273 Mbits/sec                  receiver
```

I'll close the issue for now and will retest the other setup where I had this issue. Maybe this was caused by the VMware workstation adapters or similar.
