### ISSUE TITLE
how too forwd localhost 

### ISSUE THREAD

**Issue by n3v3rsky** [nicocha30/ligolo-ng#37]
ex : - if tomcat is runnning on port 127.0.0.1:8080
how to access it

**Comment by AdMediastic** [comment]
Hey you can add listener via `listener_add` command, check out the README.md

**Comment by Pibbs** [comment]
@AdMediastic smh I've been trying to do that for a bit now but I always get "listen tcp target:8000: bind: address already in use"

**Comment by AdMediastic** [comment]
> @AdMediastic smh I've been trying to do that for a bit now but I always get "listen tcp target:8000: bind: address already in use"

Hey @Pibbs 

Can you use `ss -ntlpu` and see if there are any services running on port `8000`
If so, you can get the PID of the same and use `sudo kill <PID>` command
Make sure you run all of the above commands on target machine
If it's windows, you can use `netstat ano` and `taskkill`

And then try adding the listener in `ligolo`

I hope this helps!

**Comment by Pibbs** [comment]
@AdMediastic I appreciate the response but you missed the point. I already know there's something running on that port on the remote machine. The goal was to use ligolo to set up a reverse port forward so I could enumerate/navigate to that local port on the agent.

From what I've seen it looks like the author of ligolo is working on implementing that but hasn't yet, so I just ended up using chisel.

**Comment by nicocha30** [comment]
Duplicates #15

**Comment by nicocha30** [comment]
https://github.com/nicocha30/ligolo-ng?tab=readme-ov-file#access-to-agents-local-ports-127001
