### ISSUE TITLE
Ligolo 32bits for linux i686 ??  needed fix 

### ISSUE THREAD

**Issue by U4I5** [nicocha30/ligolo-ng#39]
(remote) root@targe:/opt/stuff# ./ligo32 -connect 172.136.40.9:4443 -ignore-cert
WARN[0000] warning, certificate validation disabled     
ERRO[0000] Connection error: dial tcp 172.136.40.9:4443: socket: invalid argument 
FATA[0000] dial tcp 172.16.40.9:4443: socket: invalid argument

**Comment by nicocha30** [comment]
Can you give me more details? Operating system? In VM?

Thanks

**Comment by KamuiID** [comment]
> Can you give me more details? Operating system? In VM?
> 
> Thanks

Hello, I'm having the same problem, in my case, I'm using metasploitable2 VM.

Linux metasploitable 2.6.24-16-server #1 SMP Thu Apr 10 13:58:00 UTC 2008 i686 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 8.04
Release:	8.04
Codename:	hardy

Thanks
