### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by JaySee95** [nicocha30/ligolo-ng#40]
Hi sorry, this might sound stupid. But i'm actually confused on how can I use ligolo for local port forwarding. Thing is, I want to access an internal web server on port 8000 on a target machine (127.0.0.1:8000). I've deployed an agent on the target machine and setup a listener, but whenever I tried to add a listener on port 8000, it shows me this error "error: listen tcp 0.0.0.0:8001: bind: address already in use"

Heres the command i used to add my listener.

listener_add --addr 127.0.0.1:8000 --to 127.0.0.1:8000

I might be confused on this part as to how to utilize it for local port forwarding. Hope someone will be able to provide me an answer for this. 

On chisel, it works like this. 

On target machine:
./chisel_linux server --reverse -port 9999

On local machine:
./chisel_linux client 192.168.188.246:9999 8000:127.0.0.1:8000

**Comment by zufukatana** [comment]
When you tried to add a listener on 8000 , you have an error telling port already in use 8001!! It's weird. Your target part is 8000 and the error showed 8001. Try listening on 0.0.0.0:8000 --to localip:8000 when adding ligolo listener. It may work

**Comment by nicocha30** [comment]
Duplicates #15

**Comment by nicocha30** [comment]
https://github.com/nicocha30/ligolo-ng?tab=readme-ov-file#access-to-agents-local-ports-127001
