### ISSUE TITLE
Need some "-exclude" option like sshutle 

### ISSUE THREAD

**Issue by test123123asdw** [nicocha30/ligolo-ng#47]
Need some "-exclude" option like sshutle , so that when the compromised machine we are  connecting to is part of the subnet you're attempting to gain access , the tool gets died.
![2023-12-07_00-19](https://github.com/nicocha30/ligolo-ng/assets/151752927/fa6bd076-bd34-4c90-b2b9-161d39b6b9f4)

**Comment by nicocha30** [comment]
Hey @test123123asdw,

I'm not sure this is simple to do. Unlike sshuttle, ligolo-ng doesn't use firewall rules to redirect traffic.
I'll close this issue.
