### ISSUE TITLE
More output in ifconfig command

### ISSUE THREAD

**Issue by yellephen** [nicocha30/ligolo-ng#48]
The problem is knowing what subnet route to add to your ligolo interface. Once a connection is up, you can run ifconfig in the ligolo console but it only gives you the IP addresses of the connected agent which only partially allows you to infer the subnet. I would have to run `ipconfig` or `ip a` on the host that will run the agent before I start the agent to know the subnet that I'll need to add to the ligolo interface.

So suggest if possible adding the subnets of the ip addresses to the output of the ifconfig command in the ligolo console.

Awesome tool by the way. Huge upgrade to any of the proxychains solutions I've used.

**Comment by nicocha30** [comment]
Hey @yellephen,

I don't really understand your issue. Ligolo-ng is already returning the current IP subnet.

```
[Agent : nchatelain@nworkstation] » ifconfig 
[...]
│ IPv4 Address │ 192.168.0.30/24
```

Can you explain a bit more?

Nicolas.
