### ISSUE TITLE
Allow specifying trusted cert fingerprint 

### ISSUE THREAD

**Issue by ecki** [nicocha30/ligolo-ng#50]
Instead of `-ignore-cert` just implement an option `--accept-cert <fingerprint>` and check the fingerprint (make sure to print it when generating a self signed cert), this way it’s least overhead and most secure option and you no longer need to deprecate it.

**Comment by nicocha30** [comment]
Good idea! I will implement this ASAP.

**Comment by nicocha30** [comment]
Implemented in Ligolo-ng v0.6!
