### ISSUE TITLE
Double Pivoting Functionality Not Working Despite Attempts to Resolve

### ISSUE THREAD

**Issue by A-BSD5** [nicocha30/ligolo-ng#53]
I encountered an issue while attempting double pivoting. Despite trying several solutions, the problem persists.

![image](https://github.com/nicocha30/ligolo-ng/assets/49440570/c874ddba-6817-4fd3-a7ea-c650baf9e981)

**Comment by nicocha30** [comment]
Create a new interface, then use the --tun newinterface arg to the start command.
