### ISSUE TITLE
Crash tunneling a Nessus scan

### ISSUE THREAD

**Issue by Biohack96** [nicocha30/ligolo-ng#54]
panic: runtime error: slice bounds out of range [:1676] with capacity 1500

goroutine 54 [running]:
github.com/nicocha30/ligolo-ng/pkg/proxy/netstack/tun.(*RWEndpoint).dispatchLoop(0xc0002edbf0)
        /home/runner/work/ligolo-ng/ligolo-ng/pkg/proxy/netstack/tun/wireguard_ep.go:67 +0x177
created by github.com/nicocha30/ligolo-ng/pkg/proxy/netstack/tun.(*RWEndpoint).Attach
        /home/runner/work/ligolo-ng/ligolo-ng/pkg/proxy/netstack/tun/wireguard_ep.go:50 +0x85

I keep getting this crash info while running a Nessus scan (on Windows) through a tunnel to a Debian machine.

**Comment by nicocha30** [comment]
Should be fixed in Ligolo-ng v0.6
