### ISSUE TITLE
[Feautre-request] Ligolo agent/proxy print version number

### ISSUE THREAD

**Issue by StayPirate** [nicocha30/ligolo-ng#59]
Currently there seems to not be any way to easily get the binary version number. I tried with the following commands, but no one is returning the agent or proxy version.

- `ligolo-agent --version`
- `ligolo-proxy --version`
- `ligolo-agent -v`
- `ligolo-proxy -v`

Would be possible to add a new option `--version` which returns information about the binary itself?

**Comment by nicocha30** [comment]
Implemented in Ligolo-ng v0.6!
