### ISSUE TITLE
Error dial tcp 127.0.0.1:port connected: connection refused

### ISSUE THREAD

**Issue by scr4sh** [nicocha30/ligolo-ng#61]
Good morgning:

I am doing an HTB prolabs, and I have this problem when I try to do a double pivot, on both machines I have root/administrator permissions. I attach screenshots, I run it from Evil-winrm... in case it influences something...
![Captura desde 2024-02-26 12-20-23](https://github.com/nicocha30/ligolo-ng/assets/160791510/5e0e1309-2ee8-4e7e-b2b2-2ad719212b85)
![Captura desde 2024-02-26 12-24-09](https://github.com/nicocha30/ligolo-ng/assets/160791510/da23b0ec-9c49-4c04-bb9e-c15973b5762a)
![Captura desde 2024-02-26 12-22-46](https://github.com/nicocha30/ligolo-ng/assets/160791510/147c5433-14e7-4830-89e7-55c2670d1ed3)

**Comment by nicocha30** [comment]
More details are needed here. Can you share some information? (Proxy Ports)

**Comment by scr4sh** [comment]
My problem comes because if on the local side (Proxy) I expect to receive connections on port 443:
./proxy -selfcert -laddr 0.0.0.0:443

Whenever you want to double pivot, you'll need to configure the listener as follows:
listener_add --addr 0.0.0.0:12000 --to 127.0.0.1:443 --tcp

And not like this, like I did:
listener_add --addr 0.0.0.0:12000 --to 127.0.0.1:13000 --tcp (the loopback port always has to match the listening port indicated in the proxy)

I didn't find anything in the documentation about it, or maybe I didn't understand it, still thank you very much for your attention, I had another "problem", with something different, I will open another thread so as not to confuse people, thank you, sorry for the inconvenience
