### ISSUE TITLE
Unable to stop listener and start tunnel 

### ISSUE THREAD

**Issue by DrorDvash** [nicocha30/ligolo-ng#63]
Hi. My issue is for v0.5.1 and v0.5.2 

1. **Unable to stop listener**
An error occurs when trying to stop a listener: `error: invalid listener id` 
I never succeeded in stopping a listener. always need to kill ligolo-ng and start over again

![image](https://github.com/nicocha30/ligolo-ng/assets/8413651/a4073904-52d9-4a3d-91ae-1a09fba17589)

------
2. **Double pivoting** - failed to start tunnel on the 2nd remote host
When trying to do double pivoting, it is not possible to start the new session and override the existing one.

![image](https://github.com/nicocha30/ligolo-ng/assets/8413651/1d860b7f-8904-4827-b311-e8d9be00c000)

while on every guide i find on google - the user asked if to switch connection
(this is a screenshot from a [guide](https://systemweakness.com/double-pivoting-for-newbies-with-ligolo-ng-4177b3f1f27b) i found)
![image](https://github.com/nicocha30/ligolo-ng/assets/8413651/d287b6f9-ddf2-4bb5-9e20-6db0d7662251)

**Comment by nicocha30** [comment]
For the first issue, I will investigate.
For the second, Ligolo-ng was updated to support multiple interfaces. If you want to start another tunnel, create a new interface and use the --tun option as said on the error message. (See Readme.md)

**Comment by DrorDvash** [comment]
> For the first issue, I will investigate. For the second, Ligolo-ng was updated to support multiple interfaces. If you want to start another tunnel, create a new interface and use the --tun option as said on the error message. (See Readme.md)

first issue - thanks, waiting for an update.

the second issue - there is no way to perform **multiple pivoting** with only 1 tun interface?
Let's say I have kali -> DC01 -> DC02 -> DC03 ->DC04, and each DC can talk to the next one only. I'm looking for a way to be able to access the whole network with only one tun interface on my kali. if I can, please show me how :)

**Comment by nicocha30** [comment]
Hey @DrorDvash,

I'm afraid not. Each tun interface is binded to an agent session. Why do you need to only use 1 tun interface?
