### ISSUE TITLE
Feature Request: Add file upload / download support over ligolo

### ISSUE THREAD

**Issue by bmigette** [nicocha30/ligolo-ng#64]
Hello, 
While there's numerous methods to copy files between different machines, sometimes the ports/protocols we can use are limited / filtered and options are limited.
I believe that the ability for ligolo to download / upload files between proxy and agent could be very handy.

Support for recursive / folder copy would also be a plus.

**Comment by nicocha30** [comment]
Hey,

I want Ligolo-ng to remain a tunneling tool, not a RAT. Sorry, I will not implement this functionality.
