### ISSUE TITLE
[ERR] yamux: keepalive failed

### ISSUE THREAD

**Issue by Mickhat** [nicocha30/ligolo-ng#65]
Running the agent on a machine gives me 

```
2024/03/18 12:51:43 [ERR] yamux: keepalive failed: i/o deadline reached
ERRO[0160] Connection error: keepalive timeout          
FATA[0160] keepalive timeout 
```

on the agent side, and 

```
2024/03/18 13:51:43 [ERR] yamux: keepalive failed: i/o deadline reached
[0456] Lost connection with agent root@XXX!   
2024/03/18 13:51:43 [ERR] yamux: Failed to read stream data: read tcp 10.XX.XX.X:11601->10.XX.XX.XX:37594: use of closed network connection
2024/03/18 13:51:43 [WARN] yamux: failed to send go away: session shutdown
```
on the proxy side. 

I see those errors when I run `nmap -sC -sV IP` and also randomly.

OS is Parrot OS

**Comment by jmhickman** [comment]
Do you mind sharing how you fixed this? These timeouts are making scans borderline impossible. I've tried setting `-T2` and such on nmap to keep the traffic load down, but it doesn't seem to help.
