### ISSUE TITLE
ERRO[0040] could not register agent, error: session shutdown 

### ISSUE THREAD

**Issue by kibanaa** [nicocha30/ligolo-ng#66]
![image](https://github.com/nicocha30/ligolo-ng/assets/61563358/dbb14a1a-808a-445a-9c5c-c3e8449434a7)
![image](https://github.com/nicocha30/ligolo-ng/assets/61563358/3fd04573-401e-44ed-81c9-daf47132b061)

*will add desc a bit latter

**Comment by nicocha30** [comment]
Hey @kibanaa do you have any antivirus/IDS/firewall running on the agent side ?

**Comment by kibanaa** [comment]
Hey @nicocha30!
Sorry for the lack of details. There is no antivirus/IDS/firewall on the agent side.

*It's Linux 32-bit, I compiled a binary for this arch.

**Comment by nicocha30** [comment]
@kibanaa

Do you have the Kernel version of the system?

**Comment by kibanaa** [comment]
Server: Linux kali 6.6.9-amd64 
Client: Linux version 2.6.24-16-server

**Comment by nicocha30** [comment]
2.6.24 is very old (2008). It seems that some syscalls are missing.
