### ISSUE TITLE
[feature request]? - running agent with admin privileges

### ISSUE THREAD

**Issue by allendemoura** [nicocha30/ligolo-ng#68]
love your tool!

as noted in the readme, nmap SYN scan packets are forwarded from the agent as TCP connect, due to the agent running without privs. however I have often found myself in a situation where I'm running the agent from a fully compromised pivot machine as SYSTEM. would be really cool to be able to enable a fully privileged mode! is this feasible/worth it?

**Comment by nicocha30** [comment]
Hey @allendemoura,

This would require a complete overhaul of ligolo-ng. The best thing is to consider using Wireguard or another more traditional VPN technology.
