### ISSUE TITLE
Connection was refused 

### ISSUE THREAD

**Issue by stavoxnetworks** [nicocha30/ligolo-ng#72]
I just wanted to see if I could get some feedback on what the cause of this may be. I see this alot when conducting nmap / autorecon scans through a tunnel. Is this due to port blocks?

![image](https://github.com/nicocha30/ligolo-ng/assets/27533789/e971f91b-770c-4466-bdf5-390e0faad4e5)

**Comment by moisha207321** [comment]
request speed is too high.  Use limitation
