### ISSUE TITLE
Self-cert flag is not defined in kali machine

### ISSUE THREAD

**Issue by abdullahabdu786** [nicocha30/ligolo-ng#74]
-selfcert flag not defined in ligolo-ng tool

**Comment by jdholtz** [comment]
What version of Ligolo-ng do you have installed on your Kali machine? You can use `apt show ligolo-ng` to show the version you're running. I currently have `0.5.2-0kali2` and the `-selfcert` flag works when I do `ligolo-proxy -selfcert` (it isn't a flag for `ligolo-agent`).
