### ISSUE TITLE
acme/autocert: missing server name

### ISSUE THREAD

**Issue by iammR0OT** [nicocha30/ligolo-ng#76]
![image](https://github.com/nicocha30/ligolo-ng/assets/74102381/32ab33cd-fd69-4e5a-98cf-377ddbde02cb)

# Client side
![image](https://github.com/nicocha30/ligolo-ng/assets/74102381/20e594ed-3d95-4f9b-a0aa-4e6ad629622b)

**Comment by nicocha30** [comment]
If connecting using an IP address : use -selfcert
If connecting using a internet facing domain: use -autocert

**Comment by iammR0OT** [comment]
Thanks man for making this awesome thing and continuously maintaining it
