### ISSUE TITLE
listener_add feature not working in v0.6

### ISSUE THREAD

**Issue by R0ttCyph3r** [nicocha30/ligolo-ng#80]
i was not able to stop listeners in v0.5.2 so i downloaded the latest version to test out i started a listener and stopped it feature was working fine but when i started new listener to test somethings and to my surprise i was not getting any results 

i get connections if port is open on netcat but if it is something like `python3 -m http.server` or sliver mtls listener

**Comment by nicocha30** [comment]
Hey @R0ttCyph3r,

Just tested on Windows 10 and Linux (with Python http.server), no issues. Can you share more details?

**Comment by quentains** [comment]
Hello there !

Just discovered this project, this is an insane tool !

I experience the exact same problem as @R0ttCyph3r . I see a connection back on a classic nc listener, but the http connection to my python webserver is impossible.

I tried to downgrade to v0.5.2, and this is working like a charm.

I'm using the same simple setup as showm above by the author (tested on a ctf environment with Kali & Windows Server 2022).

**Comment by nicocha30** [comment]
Are you using the same version between the agent and the proxy?

**Comment by quentains** [comment]
> Are you using the same version between the agent and the proxy?

Completely sure, I only downloaded the last version (v.0.6.1) binaries before trying to downgrade.

**Comment by nicocha30** [comment]
@R0ttCyph3r 

You are binding to localhost (`--to 127.0.0.1:8000`):

`listener_add --addr 0.0.0.0:8000 --to 127.0.0.1:8000`

And reaching using the external IP:

`curl http://attacker_ip:8000/something`

Wouldn't that be the problem?

I tested on every system I could, using netcat and a Python http server, over internet, and I couldn't reproduce this issue.

Can you share me a lot more details? Agent system, Proxy system, network settings, routes, command history (on ligolo and on the systems).

**Comment by quentains** [comment]
On my end I first followed the README + double checked few Youtube videos, nothing worked.

I'm sure I went for `listener_add --addr 0.0.0.0:<victim port> --to 127.0.0.1:<kali port>` and then tried to GET a file from my Kali webserver using the victim IP (in the same subnet as the second internal machine).

I may have the time to reproduce the bug and share more details later today. But I reused the exact same setup with the v.0.5.2  and it worked directly.

**Comment by R0ttCyph3r** [comment]
> @R0ttCyph3r
> 
> You are binding to localhost (`--to 127.0.0.1:8000`):
> 
> `listener_add --addr 0.0.0.0:8000 --to 127.0.0.1:8000`
> 
> And reaching using the external IP:
> 
> `curl http://attacker_ip:8000/something`
> 
> Wouldn't that be the problem?
> 
> I tested on every system I could, using netcat and a Python http server, over internet, and I couldn't reproduce this issue.
> 
> Can you share me a lot more details? Agent system, Proxy system, network settings, routes, command history (on ligolo and on the systems).


i am pretty sure this never caused me an issue prior to the latest version i am using the same commands for the past year.

i am using arch linux as host ( where proxy runs) and ubuntu as target ( where agent is running ) i checked the versions of both proxy and agent and tried on windows too didn't work can you share your commands if they differ from mine.

target is dual homed and pretty straight forward networking

**Comment by nicocha30** [comment]
@R0ttCyph3r / @quentains can you try with the new 0.6.2 version? I reverted to the old protocol.

**Comment by R0ttCyph3r** [comment]
just tested it's working fine.
