### ISSUE TITLE
Setup Ligolo-ng (version 0.6.1) for MacOS 

### ISSUE THREAD

**Issue by Yulypso** [nicocha30/ligolo-ng#81]
Hello,

Have you found a way to create a "utun[0-9]" interface for the Ligolo-ng proxy server on macOS (MacOS: 14.4.1)? 
The command "interface_create" doesn't exist in version ligolo-ng_proxy_0.6.1_darwin_amd64.

In version 0.6.1, the agent "ligolo-ng_agent_0.6.1_darwin_amd64" can bind to the "ligolo-ng_proxy_0.6.1_darwin_amd64" server, however, there is no option to create a tunnel and relay the connection to the agent using the "tunnel_start" command.

**Comment by nicocha30** [comment]
`tunnel_start --tun utun4`

**Comment by Hexix23** [comment]
From my end still not working properly.

I manage to create the utun interface but didnt get any IP and when I tried to assign the range that I want to tunnel didnt work.

Any idea?

**Comment by nicocha30** [comment]
@Hexix23 can you share more details? Do you have any errors?

**Comment by Hexix23** [comment]
@nicocha30 yes ofc.

So I have a windows VM hosting the `agent`
![image](https://github.com/nicocha30/ligolo-ng/assets/62616592/6bfdf639-d317-4ab0-99a2-0a239afd8958)

And my MacOS hosting the `proxy`
![image](https://github.com/nicocha30/ligolo-ng/assets/62616592/aafc94ca-0162-4dea-8b00-18f6024d0921)

And from here everything works like a charms and the agent connected to the server.

I created the utun interfaced with the new funcionality and works fine:
![image](https://github.com/nicocha30/ligolo-ng/assets/62616592/128d3cf8-af1f-49f9-b31c-f3ad51ebded3)

And you can see the interface through `ifconfig`
![image](https://github.com/nicocha30/ligolo-ng/assets/62616592/e480ede4-cf20-49f2-a149-fe9cff00e4b6)

But whatever you try to add a specific IP didnt work.

How did you do on your site? On your mac mini worked?

Thnks in advance! And let me know if I can help with any macos development

**Comment by nicocha30** [comment]
Did you tried:

```
$ sudo ifconfig utun4 alias [random_ip] 255.255.255.0
$ sudo route add -net 192.168.2.0/24 interface utun4
```

As explained in README?

**Comment by Hexix23** [comment]
Yes.

And even if I assign the route and an IP within the range, the tunneling is not done well and I do not get through the machine to the "internal" network.

**Comment by nicocha30** [comment]
Can you run the proxy with "-v" and show me the result? On my Mac Mini it worked, but I couldn't do much testing.

**Comment by MelForze** [comment]
> Yes.
> 
> And even if I assign the route and an IP within the range, the tunneling is not done well and I do not get through the machine to the "internal" network.

You need to create a new utun, which you don't have in interfaces (ifconfig or ip a). I had utun1-8 and created utun9 
```
tunnel_start --tun utun9
``` 
then added ip and routes and everything worked fine.
