### ISSUE TITLE
Access agent local ports (magic CIDR) not working

### ISSUE THREAD

**Issue by MaccariTA** [nicocha30/ligolo-ng#82]
**Server version: 0.6
Client version: 0.6.1**
![image](https://github.com/nicocha30/ligolo-ng/assets/20310946/afa26633-95f5-4079-bfd2-f5560c0b66c8)

**Comment by nicocha30** [comment]
![image](https://github.com/nicocha30/ligolo-ng/assets/31402213/aff513c9-a856-4529-891e-dc5a6d57f6c8)

Everything is working fine for me. Did you start the tunnel?

**Comment by MaccariTA** [comment]
@nicocha30 the tunnel is started, you can see the ping works for 172.16.226.254

**Comment by nicocha30** [comment]
Don't rely on ping, try accessing a local port

**Comment by MaccariTA** [comment]
@nicocha30 I can definitely confirm it's working
![image](https://github.com/nicocha30/ligolo-ng/assets/20310946/eba8327b-3dbe-4a09-94c9-aa4544de4026)

**Comment by MaccariTA** [comment]
I can confirm it's working properly. It's specifically `ping` not working.

**Comment by nicocha30** [comment]
Hi @MaccariTA
Thanks for this issue, it raised a problem in ping processing for magicIP. Now version 0.6.2 should fix the problem.
