### ISSUE TITLE
Some mistake in readme

### ISSUE THREAD

**Issue by MelForze** [nicocha30/ligolo-ng#83]
Hi, you should change the command in the readme to add a route on macOS. In the readme 
```
sudo route add -net 192.168.2.0/24 interface utun4
```
Should be: 
```
sudo route add -net 192.168.2.0/24 -interface utun4
```

And thank you so much for adding macOS support :)

**Comment by nicocha30** [comment]
Woops! My bad. I will update the README ASAP.
Have you tested Ligolo-ng on MacOS? I will need feedback since I have not been able to test it extensively.

**Comment by MelForze** [comment]
> Woops! My bad. I will update the README ASAP. Have you tested Ligolo-ng on MacOS? I will need feedback since I have not been able to test it extensively.

Yeah, I did. Everything works fine, haven't noticed anything yet :) 
If I notice anything, I'll post the issue later!
