### ISSUE TITLE
Could not register agent

### ISSUE THREAD

**Issue by 9gab** [nicocha30/ligolo-ng#84]
Hello, 

I'm trying to perform a double pivot, however, I'm getting the following error:

<img width="991" alt="Screenshot 2024-07-03 at 15 46 08" src="https://github.com/nicocha30/ligolo-ng/assets/174647497/1a4543f6-1264-4e78-9433-19a31882b97e">

server and agent = 0.6.1

**Comment by nicocha30** [comment]
These are mainly routing problems, such as adding a route from the second pivot that overlaps the first route.

**Comment by 9gab** [comment]
Thanks for the reply. I'm doing the same box from this tutorial, [,]((https://4pfsec.com/ligolo)) I followed the steps but always get this error at the end.

**Comment by 9gab** [comment]
Thanks for the reply. I'm doing the same box from this tutorial, [https://4pfsec.com/ligolo] , I followed the steps but always get this error at the end.

**Comment by 9gab** [comment]
Thanks for the reply. I'm doing the same box from this tutorial, [ligolo](https://4pfsec.com/ligolo) , I followed the steps but always get this error at the end.

**Comment by 9gab** [comment]
Sure, here it is:

<img width="808" alt="Screenshot 2024-07-04 at 10 54 14" src="https://github.com/nicocha30/ligolo-ng/assets/174647497/bafc9bb9-8ed3-4b2e-987f-eec5f8b07820">

I'm starting to think that must be something on my side. Before, when doing the box, I was able to create listeners which I used to transfer files, through the pivot, from my attack box to other hosts and it worked all good. Now, when I try to do it I get the following error:

<img width="1091" alt="Screenshot 2024-07-04 at 10 59 00" src="https://github.com/nicocha30/ligolo-ng/assets/174647497/f3cfecef-72b0-430e-a90b-5e121e5f5af4">

**Comment by 9gab** [comment]
Solved the problem. Actually it has to do with version 0.6.1
 
Tried with 0.5.2 and it worked flawlessly.

**Comment by nathan-rabet** [comment]
Same issue, still not solved in version `0.6.2`.

**Comment by nicocha30** [comment]
@nathan-rabet could you share more details? OS version, setup, commands?
Can you run Ligolo-ng with the "-v" flag and give me the error?

Thanks

**Comment by nathan-rabet** [comment]
Tried to register an agent: didn't work.
Reboot, then register the same agent: did work.

(weird).

I think this issue can be closed then.
