### ISSUE TITLE
Cannot connect to proxy (from agent) when interface cannot be found

### ISSUE THREAD

**Issue by 0xNoport** [nicocha30/ligolo-ng#88]
I had the redis service installed on linux and as redis user you cannot run ifconfig or ip addr (at least not on the machine that i was on) so it didn't let me connect to the proxy... Is there any workaround/possible fix? As any other user i was able to run ip addr and then also was able to connect to the proxy. (the machine i was working on was PG Practice: "Readys")

**Comment by nicocha30** [comment]
Hey @0xNoport
Do you have any idea how I can reproduce this issue?

**Comment by 0xNoport** [comment]
No, I only know that it appears if the redis service can't list the interfaces.

**Comment by nicocha30** [comment]
Tested on Redis Docker, without ifconfig/ip addr, no issues. Ligolo-ng does not use these commands.
