### ISSUE TITLE
Feature request: interactive route choice when using route deletion feature

### ISSUE THREAD

**Issue by Aetiuss** [nicocha30/ligolo-ng#91]
Hello,

Thanks for the great tool!

On the proxy server it would be nice that when typing 'route_del' (or alias) the user is prompted with the current routes so to chose the ones he wants to delete,

Also a feature to delete all routes at the same time would be useful.

BTW: You should add an issue template.

**Comment by Aetiuss** [comment]
Feature example: https://raw.githubusercontent.com/ShutdownRepo/shellerator/master/assets/example-menus.gif

**Comment by nicocha30** [comment]
Hey! The next Ligolo-ng version will implement this functionality.

**Comment by nicocha30** [comment]
Done on Ligolo-ng v0.7.0-alpha
