### ISSUE TITLE
Constant crashing when tunneling Certipy

### ISSUE THREAD

**Issue by init5-SF** [nicocha30/ligolo-ng#92]
Hello, I have just started using Ligolo-ng, the tool works great with all my Kali tools, but it always crashes if I use certipy.

I tried these syntaxes:

`certipy shadow auto -k -no-pass -dc-ip 172.16.67.1 -ns 172.16.67.1 -account 'cb-store' -target cb-dc.certbulk.cb.corp -debug`

`certipy find -u student18 -p D8R5rGu7PwzKBwXf -dc-ip 172.16.67.1 -ns 172.16.67.1`

and I always get the same crash, the agent on the foothold machine crashes with the below message:
```
C:\ADCS\Tools>lig.exe -connect 172.16.99.18:11601 -ignore-cert
time="2024-07-20T16:10:53-07:00" level=warning msg="warning, certificate validation disabled"
time="2024-07-20T16:10:53-07:00" level=info msg="Connection established" addr="172.16.99.18:11601"
2024/07/21 06:07:04 [ERR] yamux: Failed to write header: write tcp 172.16.100.18:31842->172.16.99.18:11601: use of closed network connection
time="2024-07-21T06:07:04-07:00" level=error msg="Connection error: EOF"
time="2024-07-21T06:07:04-07:00" level=fatal msg=EOF
```

The tunneling config is done correctly and all other tools like nmap, Evil-WinRM, betexec are working flawlessly, only certipy is breaking the tunnel.

Any suggestions how to fix this?

**Comment by hexa-alt** [comment]
I have this same issue.  'Use of closed connection' on every spawned listener

**Comment by nicocha30** [comment]
Can you try using the command line argument `-v` so I can see more details?

**Comment by init5-SF** [comment]
> Can you try using the command line argument `-v` so I can see more details?

I have absolutely no idea what happened, but I can't reproduce the error.
I didn't change a single thing, but the tunnel no longer fails and certipy works ok now!🫤
